-- MySQL Script generated by MySQL Workbench
-- mar 28 dic 2021 00:18:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_db` DEFAULT CHARACTER SET utf8 ;
USE `empresa_db` ;

-- -----------------------------------------------------
-- Table `empresa_db`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `mail` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Fotos` (
  `idFotos` INT NOT NULL,
  `Imagen` LONGBLOB NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Tecnicos` (
  `idTecnico` INT NOT NULL AUTO_INCREMENT,
  `cuil` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `foto` INT NULL,
  `mail` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idTecnico`),
  CONSTRAINT `foto`
    FOREIGN KEY ()
    REFERENCES `empresa_db`.`Fotos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Especialidades` (
  `idEspecialidades` INT NOT NULL AUTO_INCREMENT,
  `nombreEspecialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecialidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo_Empleados_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo_Empleados`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo1` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo1_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo1_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo2` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo2_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo2_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo3` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo3_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo3_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Tecnicos_Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Tecnicos_Especialidades` (
  `Tecnicos_cuil` INT NOT NULL,
  `Especialidades_idEspecialidades` INT NOT NULL,
  PRIMARY KEY (`Tecnicos_cuil`, `Especialidades_idEspecialidades`),
  INDEX `fk_Tecnicos_has_Especialidades_Especialidades1_idx` (`Especialidades_idEspecialidades` ASC) VISIBLE,
  INDEX `fk_Tecnicos_has_Especialidades_Tecnicos1_idx` (`Tecnicos_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Tecnicos1`
    FOREIGN KEY (`Tecnicos_cuil`)
    REFERENCES `empresa_db`.`Tecnicos` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Especialidades1`
    FOREIGN KEY (`Especialidades_idEspecialidades`)
    REFERENCES `empresa_db`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Nombre` VARCHAR(100) NULL,
  PRIMARY KEY (`idServicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`ReporteIncidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`ReporteIncidentes` (
  `idReporteIncidentes` INT NOT NULL,
  `usuario` INT NOT NULL,
  `cliente` INT NOT NULL,
  `tecnico` INT NOT NULL,
  `servicio` INT NULL,
  `descripcion` VARCHAR(1000) NULL,
  `tipo` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `considereaciones` VARCHAR(1000) NULL,
  PRIMARY KEY (`idReporteIncidentes`),
  INDEX `cuilCliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `cuilTecnico_idx` (`tecnico` ASC) VISIBLE,
  INDEX `cuilEmpleado_idx` (`usuario` ASC) VISIBLE,
  INDEX `servicio_idx` (`servicio` ASC) VISIBLE,
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`usuario`)
    REFERENCES `empresa_db`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `empresa_db`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTecnico`
    FOREIGN KEY (`tecnico`)
    REFERENCES `empresa_db`.`Tecnicos` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idServicio`
    FOREIGN KEY (`servicio`)
    REFERENCES `empresa_db`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Tecnico-Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Tecnico-Especialidad` (
  `idTecnico` INT NOT NULL,
  `idEspecialidades` INT NOT NULL,
  PRIMARY KEY (`idTecnico`, `idEspecialidades`),
  INDEX `fk_Tecnicos_has_Especialidades_Especialidades2_idx` (`idEspecialidades` ASC) VISIBLE,
  INDEX `fk_Tecnicos_has_Especialidades_Tecnicos2_idx` (`idTecnico` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Tecnicos2`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `empresa_db`.`Tecnicos` (`idTecnico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Especialidades2`
    FOREIGN KEY (`idEspecialidades`)
    REFERENCES `empresa_db`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Cliente-Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Cliente-Servicio` (
  `idCliente` INT NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idServicio`),
  INDEX `fk_Clientes_has_Servicios_Servicios1_idx` (`idServicio` ASC) VISIBLE,
  INDEX `fk_Clientes_has_Servicios_Clientes1_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_has_Servicios_Clientes1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `empresa_db`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Servicios_Servicios1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `empresa_db`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
