-- MySQL Script generated by MySQL Workbench
-- Thu Dec  2 10:40:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `empresa_db` DEFAULT CHARACTER SET utf8 ;
USE `empresa_db` ;

-- -----------------------------------------------------
-- Table `empresa_db`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Clientes` (
  `cuil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`cuil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Tecnicos` (
  `cuil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  PRIMARY KEY (`cuil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Directivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Directivo` (
  `idDirectivo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDirectivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados` (
  `cuil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `idDirectivo` INT NOT NULL,
  PRIMARY KEY (`cuil`),
  INDEX `idDirecitvo_idx` (`idDirectivo` ASC) VISIBLE,
  CONSTRAINT `idDirecitvo`
    FOREIGN KEY (`idDirectivo`)
    REFERENCES `empresa_db`.`Directivo` (`idDirectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Especialidades` (
  `idEspecialidades` INT NOT NULL AUTO_INCREMENT,
  `nombreEspecialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspecialidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo_Directivo1_idx` (`Directivo_idDirectivo` ASC) VISIBLE,
  INDEX `fk_Empleados_has_Directivo_Empleados_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo_Empleados`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Empleados` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_has_Directivo_Directivo1`
    FOREIGN KEY (`Directivo_idDirectivo`)
    REFERENCES `empresa_db`.`Directivo` (`idDirectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo1` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo1_Directivo1_idx` (`Directivo_idDirectivo` ASC) VISIBLE,
  INDEX `fk_Empleados_has_Directivo1_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo1_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Empleados` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_has_Directivo1_Directivo1`
    FOREIGN KEY (`Directivo_idDirectivo`)
    REFERENCES `empresa_db`.`Directivo` (`idDirectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo2` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo2_Directivo1_idx` (`Directivo_idDirectivo` ASC) VISIBLE,
  INDEX `fk_Empleados_has_Directivo2_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo2_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Empleados` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_has_Directivo2_Directivo1`
    FOREIGN KEY (`Directivo_idDirectivo`)
    REFERENCES `empresa_db`.`Directivo` (`idDirectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Empleados_has_Directivo3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Empleados_has_Directivo3` (
  `Empleados_cuil` INT NOT NULL,
  `Directivo_idDirectivo` INT NOT NULL,
  PRIMARY KEY (`Empleados_cuil`, `Directivo_idDirectivo`),
  INDEX `fk_Empleados_has_Directivo3_Directivo1_idx` (`Directivo_idDirectivo` ASC) VISIBLE,
  INDEX `fk_Empleados_has_Directivo3_Empleados1_idx` (`Empleados_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Empleados_has_Directivo3_Empleados1`
    FOREIGN KEY (`Empleados_cuil`)
    REFERENCES `empresa_db`.`Empleados` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empleados_has_Directivo3_Directivo1`
    FOREIGN KEY (`Directivo_idDirectivo`)
    REFERENCES `empresa_db`.`Directivo` (`idDirectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`Tecnicos_Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`Tecnicos_Especialidades` (
  `Tecnicos_cuil` INT NOT NULL,
  `Especialidades_idEspecialidades` INT NOT NULL,
  PRIMARY KEY (`Tecnicos_cuil`, `Especialidades_idEspecialidades`),
  INDEX `fk_Tecnicos_has_Especialidades_Especialidades1_idx` (`Especialidades_idEspecialidades` ASC) VISIBLE,
  INDEX `fk_Tecnicos_has_Especialidades_Tecnicos1_idx` (`Tecnicos_cuil` ASC) VISIBLE,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Tecnicos1`
    FOREIGN KEY (`Tecnicos_cuil`)
    REFERENCES `empresa_db`.`Tecnicos` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tecnicos_has_Especialidades_Especialidades1`
    FOREIGN KEY (`Especialidades_idEspecialidades`)
    REFERENCES `empresa_db`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa_db`.`ReporteIncidentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa_db`.`ReporteIncidentes` (
  `idReporteIncidentes` INT NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cuilEmpleado` INT NOT NULL,
  `cuilCliente` INT NOT NULL,
  `cuilTecnico` INT NOT NULL,
  PRIMARY KEY (`idReporteIncidentes`),
  INDEX `cuilCliente_idx` (`cuilCliente` ASC) VISIBLE,
  INDEX `cuilTecnico_idx` (`cuilTecnico` ASC) VISIBLE,
  INDEX `cuilEmpleado_idx` (`cuilEmpleado` ASC) VISIBLE,
  CONSTRAINT `cuilEmpleado`
    FOREIGN KEY (`cuilEmpleado`)
    REFERENCES `empresa_db`.`Empleados` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuilCliente`
    FOREIGN KEY (`cuilCliente`)
    REFERENCES `empresa_db`.`Clientes` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cuilTecnico`
    FOREIGN KEY (`cuilTecnico`)
    REFERENCES `empresa_db`.`Tecnicos` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;